Added a new tutorial
webiny/write-with-webiny pull request #110
Opened 2022-11-09 06:48 UTC by kmaurice012

2022-11-09 06:49 UTC, kmaurice012 commented
A blog with Webiny and Eleventy

2022-11-10 09:51 UTC, endymion1818 requested changes

2022-11-10 09:51 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_includes/layouts/post.njk
> +                {# <time datetime="{{ post.date }}">{{ post.date | readableDate }}</time> #}
Why is this commented out? Should it be removed?

2022-11-10 09:51 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_data/site.json
> +  "description": "A simple blog with awesome content"
```suggestion
  "title": "Source Webiny Headless CMS",
  "url": "https://example.com/",
  "language": "en-US",
  "description": "An Eleventy blog template for sourcing content from Webiny Headless CMS"
```

2022-11-10 09:51 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_site/about/index.html
> +  </main>
Please format the code, there are a lot of gaps and irregularities, here for example.

2022-11-10 09:52 UTC, endymion1818 commented
Hi @kmaurice012, a few things to tidy up but nothing major. Thanks for the PR!

2022-11-10 10:44 UTC, kmaurice012 commented
Done

2022-11-10 10:47 UTC, endymion1818 reviewed
Nearly there!

2022-11-10 10:47 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_site/indeex/index.html
> +<h1>Hello, world!</h1>
Is this file spurious?

2022-11-10 10:47 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_site/index.html
> +<section class="hero is-medium is-primary is-bold">
formatting

2022-11-10 10:47 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_site/index.html
> +</html>
formatting

2022-11-10 10:47 UTC, endymion1818 commented on tutorials/EleventyWebinyBlog/_site/posts/first-post/index.html
> +
formatting

2022-11-10 10:57 UTC, kmaurice012 commented
Done

2022-11-10 10:58 UTC, endymion1818 approved these changes

2022-12-29 15:40 UTC, merged