Personal blog using Hugo and Webiny
webiny/write-with-webiny pull request #112
Opened 2022-11-09 13:51 UTC by AmenyaZ

2022-11-10 09:40 UTC, endymion1818 requested changes
Thanks @AmenyaZ for this code, please could you remove the node_modules you've checked in? You will need to add a `.gitignore` to the project root, add the **node_modules** folder and then delete it from the git history and push again.

2022-11-10 14:36 UTC, AmenyaZ commented
I made a second push. Please check the commit

2022-11-16 08:58 UTC, endymion1818 requested changes
Nearly there!

2022-11-16 08:58 UTC, endymion1818 commented on tutorials/hugo-blog/config.toml
> +baseURL = 'https://dgpcvq8nrbk6c.cloudfront.net/cms/read/en-US'
Please remove this too

2022-11-16 09:38 UTC, closed without merging